/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace Escrow {
  export type MilestoneFundingStruct = {
    totalContributed: BigNumberish;
    isFullyFunded: boolean;
  };

  export type MilestoneFundingStructOutput = [BigNumber, boolean] & {
    totalContributed: BigNumber;
    isFullyFunded: boolean;
  };

  export type TransactionHistoryStruct = {
    workers: BigNumberish;
    materialCost: BigNumberish;
    daysTaken: BigNumberish;
  };

  export type TransactionHistoryStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber
  ] & { workers: BigNumber; materialCost: BigNumber; daysTaken: BigNumber };
}

export interface EscrowInterface extends utils.Interface {
  functions: {
    "TotalContributions(uint256)": FunctionFragment;
    "VerifyTransaction(uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "approveCampaign(uint256)": FunctionFragment;
    "campaignContributions(uint256,address)": FunctionFragment;
    "campaigns(uint256)": FunctionFragment;
    "confirmBilling(uint256,uint256)": FunctionFragment;
    "contributeToCampaign(uint256,uint256)": FunctionFragment;
    "createCampaign(address,uint256,uint256)": FunctionFragment;
    "daoAddress()": FunctionFragment;
    "donorSpecs(uint256,uint256)": FunctionFragment;
    "escAccount()": FunctionFragment;
    "getCampaignStatus(uint256)": FunctionFragment;
    "getDaoAddress()": FunctionFragment;
    "getDetails(uint256)": FunctionFragment;
    "getMilestoneCount(uint256)": FunctionFragment;
    "getMilestoneDetails(uint256,uint256)": FunctionFragment;
    "getTransactionHistory(uint256,uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "payServiceProvider(uint256,uint256,address)": FunctionFragment;
    "rejectCampaign(uint256)": FunctionFragment;
    "releaseMilestone(uint256,uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "requestService(uint256,uint256,string,address)": FunctionFragment;
    "serviceProviders(string)": FunctionFragment;
    "setDAOAddress(address)": FunctionFragment;
    "setMilestoneDescription(uint256,uint256,string)": FunctionFragment;
    "setMilestoneStatus(uint256,uint256,uint8)": FunctionFragment;
    "submitBilling(uint256,uint256,uint256,uint256)": FunctionFragment;
    "submitServiceCompletion(uint256,uint256,address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "viewCampaignDetails(uint256)": FunctionFragment;
    "viewMilestoneDetails(uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "TotalContributions"
      | "VerifyTransaction"
      | "approveCampaign"
      | "campaignContributions"
      | "campaigns"
      | "confirmBilling"
      | "contributeToCampaign"
      | "createCampaign"
      | "daoAddress"
      | "donorSpecs"
      | "escAccount"
      | "getCampaignStatus"
      | "getDaoAddress"
      | "getDetails"
      | "getMilestoneCount"
      | "getMilestoneDetails"
      | "getTransactionHistory"
      | "owner"
      | "payServiceProvider"
      | "rejectCampaign"
      | "releaseMilestone"
      | "renounceOwnership"
      | "requestService"
      | "serviceProviders"
      | "setDAOAddress"
      | "setMilestoneDescription"
      | "setMilestoneStatus"
      | "submitBilling"
      | "submitServiceCompletion"
      | "transferOwnership"
      | "viewCampaignDetails"
      | "viewMilestoneDetails"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "TotalContributions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "VerifyTransaction",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "approveCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignContributions",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmBilling",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributeToCampaign",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "daoAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "donorSpecs",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escAccount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDaoAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestoneCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestoneDetails",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionHistory",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payServiceProvider",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseMilestone",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestService",
    values: [BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "serviceProviders",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setDAOAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setMilestoneDescription",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setMilestoneStatus",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBilling",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitServiceCompletion",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "viewCampaignDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "viewMilestoneDetails",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "TotalContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VerifyTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmBilling",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributeToCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "daoAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "donorSpecs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "escAccount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDaoAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDetails", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMilestoneCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMilestoneDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payServiceProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serviceProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDAOAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMilestoneDescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMilestoneStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitBilling",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitServiceCompletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewCampaignDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewMilestoneDetails",
    data: BytesLike
  ): Result;

  events: {
    "AllMilestonesReceived(uint256)": EventFragment;
    "BillingConfirmed(uint256,uint256)": EventFragment;
    "BillingSubmitted(uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "CampaignCompleted(uint256)": EventFragment;
    "CampaignCreated(uint256,address,uint256)": EventFragment;
    "CampaignStatusChanged(uint256,uint8)": EventFragment;
    "ContributionReceived(address,uint256,uint256)": EventFragment;
    "MilestoneDescriptionUpdated(uint256,uint256,string)": EventFragment;
    "MilestoneReached(uint256,uint256)": EventFragment;
    "MilestoneUpdated(uint256,uint256,uint8)": EventFragment;
    "MilestoneVerified(uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RefundIssued(uint256,address,uint256)": EventFragment;
    "ServiceCompletionSubmitted(uint256,uint256,address)": EventFragment;
    "ServiceProviderPaid(uint256,uint256,address,uint256,uint256)": EventFragment;
    "ServiceRequested(uint256,uint256,string,address)": EventFragment;
    "TransactionHistUpdate(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AllMilestonesReceived"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BillingConfirmed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BillingSubmitted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CampaignCompleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CampaignCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CampaignStatusChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContributionReceived"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "MilestoneDescriptionUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MilestoneReached"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MilestoneUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MilestoneVerified"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RefundIssued"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ServiceCompletionSubmitted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ServiceProviderPaid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ServiceRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransactionHistUpdate"): EventFragment;
}

export interface AllMilestonesReceivedEventObject {
  campaignId: BigNumber;
}
export type AllMilestonesReceivedEvent = TypedEvent<
  [BigNumber],
  AllMilestonesReceivedEventObject
>;

export type AllMilestonesReceivedEventFilter =
  TypedEventFilter<AllMilestonesReceivedEvent>;

export interface BillingConfirmedEventObject {
  campaignId: BigNumber;
  milestoneIndex: BigNumber;
}
export type BillingConfirmedEvent = TypedEvent<
  [BigNumber, BigNumber],
  BillingConfirmedEventObject
>;

export type BillingConfirmedEventFilter =
  TypedEventFilter<BillingConfirmedEvent>;

export interface BillingSubmittedEventObject {
  campaignId: BigNumber;
  milestoneIndex: BigNumber;
  workersCost: BigNumber;
  materialsCost: BigNumber;
  totalCost: BigNumber;
}
export type BillingSubmittedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  BillingSubmittedEventObject
>;

export type BillingSubmittedEventFilter =
  TypedEventFilter<BillingSubmittedEvent>;

export interface CampaignCompletedEventObject {
  campaignId: BigNumber;
}
export type CampaignCompletedEvent = TypedEvent<
  [BigNumber],
  CampaignCompletedEventObject
>;

export type CampaignCompletedEventFilter =
  TypedEventFilter<CampaignCompletedEvent>;

export interface CampaignCreatedEventObject {
  campaignId: BigNumber;
  beneficiary: string;
  totalAmount: BigNumber;
}
export type CampaignCreatedEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  CampaignCreatedEventObject
>;

export type CampaignCreatedEventFilter = TypedEventFilter<CampaignCreatedEvent>;

export interface CampaignStatusChangedEventObject {
  campaignId: BigNumber;
  status: number;
}
export type CampaignStatusChangedEvent = TypedEvent<
  [BigNumber, number],
  CampaignStatusChangedEventObject
>;

export type CampaignStatusChangedEventFilter =
  TypedEventFilter<CampaignStatusChangedEvent>;

export interface ContributionReceivedEventObject {
  contributor: string;
  campaignId: BigNumber;
  targetAmount: BigNumber;
}
export type ContributionReceivedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  ContributionReceivedEventObject
>;

export type ContributionReceivedEventFilter =
  TypedEventFilter<ContributionReceivedEvent>;

export interface MilestoneDescriptionUpdatedEventObject {
  campaignId: BigNumber;
  milestoneIndex: BigNumber;
  description: string;
}
export type MilestoneDescriptionUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  MilestoneDescriptionUpdatedEventObject
>;

export type MilestoneDescriptionUpdatedEventFilter =
  TypedEventFilter<MilestoneDescriptionUpdatedEvent>;

export interface MilestoneReachedEventObject {
  campaignId: BigNumber;
  milestoneIndex: BigNumber;
}
export type MilestoneReachedEvent = TypedEvent<
  [BigNumber, BigNumber],
  MilestoneReachedEventObject
>;

export type MilestoneReachedEventFilter =
  TypedEventFilter<MilestoneReachedEvent>;

export interface MilestoneUpdatedEventObject {
  campaignId: BigNumber;
  milestoneIndex: BigNumber;
  status: number;
}
export type MilestoneUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber, number],
  MilestoneUpdatedEventObject
>;

export type MilestoneUpdatedEventFilter =
  TypedEventFilter<MilestoneUpdatedEvent>;

export interface MilestoneVerifiedEventObject {
  campaignId: BigNumber;
  milestoneIndex: BigNumber;
}
export type MilestoneVerifiedEvent = TypedEvent<
  [BigNumber, BigNumber],
  MilestoneVerifiedEventObject
>;

export type MilestoneVerifiedEventFilter =
  TypedEventFilter<MilestoneVerifiedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface RefundIssuedEventObject {
  id: BigNumber;
  contributor: string;
  refundAmt: BigNumber;
}
export type RefundIssuedEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  RefundIssuedEventObject
>;

export type RefundIssuedEventFilter = TypedEventFilter<RefundIssuedEvent>;

export interface ServiceCompletionSubmittedEventObject {
  campaignId: BigNumber;
  milestoneIndex: BigNumber;
  serviceProvider: string;
}
export type ServiceCompletionSubmittedEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  ServiceCompletionSubmittedEventObject
>;

export type ServiceCompletionSubmittedEventFilter =
  TypedEventFilter<ServiceCompletionSubmittedEvent>;

export interface ServiceProviderPaidEventObject {
  campaignId: BigNumber;
  milestoneIndex: BigNumber;
  serviceProvider: string;
  amount: BigNumber;
  remainingAmount: BigNumber;
}
export type ServiceProviderPaidEvent = TypedEvent<
  [BigNumber, BigNumber, string, BigNumber, BigNumber],
  ServiceProviderPaidEventObject
>;

export type ServiceProviderPaidEventFilter =
  TypedEventFilter<ServiceProviderPaidEvent>;

export interface ServiceRequestedEventObject {
  campaignId: BigNumber;
  milestoneIndex: BigNumber;
  serviceDescription: string;
  serviceProvider: string;
}
export type ServiceRequestedEvent = TypedEvent<
  [BigNumber, BigNumber, string, string],
  ServiceRequestedEventObject
>;

export type ServiceRequestedEventFilter =
  TypedEventFilter<ServiceRequestedEvent>;

export interface TransactionHistUpdateEventObject {
  campaignId: BigNumber;
  milestoneIndex: BigNumber;
}
export type TransactionHistUpdateEvent = TypedEvent<
  [BigNumber, BigNumber],
  TransactionHistUpdateEventObject
>;

export type TransactionHistUpdateEventFilter =
  TypedEventFilter<TransactionHistUpdateEvent>;

export interface Escrow extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EscrowInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    TotalContributions(
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [Escrow.MilestoneFundingStructOutput[]] & {
        contributions: Escrow.MilestoneFundingStructOutput[];
      }
    >;

    VerifyTransaction(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      _workers: BigNumberish,
      _materialCost: BigNumberish,
      _daysTaken: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    approveCampaign(
      _campaignId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    campaignContributions(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    campaigns(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, number, BigNumber, BigNumber] & {
        id: BigNumber;
        beneficiary: string;
        totalAmount: BigNumber;
        status: number;
        currentIndex: BigNumber;
        totalContributions: BigNumber;
      }
    >;

    confirmBilling(
      campaignId: BigNumberish,
      milestoneIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    contributeToCampaign(
      _campaignId: BigNumberish,
      _amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    createCampaign(
      _beneficiary: string,
      _totalAmount: BigNumberish,
      _milestoneCount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    daoAddress(overrides?: CallOverrides): Promise<[string]>;

    donorSpecs(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { targetAmount: BigNumber }>;

    escAccount(overrides?: CallOverrides): Promise<[string]>;

    getCampaignStatus(
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getDaoAddress(overrides?: CallOverrides): Promise<[string]>;

    getDetails(
      campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMilestoneCount(
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMilestoneDetails(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, number] & { amount: BigNumber; status: number }>;

    getTransactionHistory(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[Escrow.TransactionHistoryStructOutput]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    payServiceProvider(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      _serviceProvider: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    rejectCampaign(
      _campaignId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    releaseMilestone(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    requestService(
      campaignId: BigNumberish,
      milestoneIndex: BigNumberish,
      serviceDescription: string,
      serviceProvider: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    serviceProviders(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setDAOAddress(
      _daoAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setMilestoneDescription(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      _description: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setMilestoneStatus(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      _status: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    submitBilling(
      campaignId: BigNumberish,
      milestoneIndex: BigNumberish,
      workersCost: BigNumberish,
      materialsCost: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    submitServiceCompletion(
      campaignId: BigNumberish,
      milestoneIndex: BigNumberish,
      serviceProvider: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    viewCampaignDetails(
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, number, BigNumber] & {
        id: BigNumber;
        beneficiary: string;
        totalAmount: BigNumber;
        status: number;
        milestoneCount: BigNumber;
      }
    >;

    viewMilestoneDetails(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, BigNumber, BigNumber, BigNumber] & {
        amount: BigNumber;
        status: number;
        workers: BigNumber;
        materialCost: BigNumber;
        daysTaken: BigNumber;
      }
    >;
  };

  TotalContributions(
    _campaignId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<Escrow.MilestoneFundingStructOutput[]>;

  VerifyTransaction(
    _campaignId: BigNumberish,
    _milestoneIndex: BigNumberish,
    _workers: BigNumberish,
    _materialCost: BigNumberish,
    _daysTaken: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  approveCampaign(
    _campaignId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  campaignContributions(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  campaigns(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber, number, BigNumber, BigNumber] & {
      id: BigNumber;
      beneficiary: string;
      totalAmount: BigNumber;
      status: number;
      currentIndex: BigNumber;
      totalContributions: BigNumber;
    }
  >;

  confirmBilling(
    campaignId: BigNumberish,
    milestoneIndex: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  contributeToCampaign(
    _campaignId: BigNumberish,
    _amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  createCampaign(
    _beneficiary: string,
    _totalAmount: BigNumberish,
    _milestoneCount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  daoAddress(overrides?: CallOverrides): Promise<string>;

  donorSpecs(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  escAccount(overrides?: CallOverrides): Promise<string>;

  getCampaignStatus(
    _campaignId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  getDaoAddress(overrides?: CallOverrides): Promise<string>;

  getDetails(
    campaignId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getMilestoneCount(
    _campaignId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getMilestoneDetails(
    _campaignId: BigNumberish,
    _milestoneIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, number] & { amount: BigNumber; status: number }>;

  getTransactionHistory(
    _campaignId: BigNumberish,
    _milestoneIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<Escrow.TransactionHistoryStructOutput>;

  owner(overrides?: CallOverrides): Promise<string>;

  payServiceProvider(
    _campaignId: BigNumberish,
    _milestoneIndex: BigNumberish,
    _serviceProvider: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  rejectCampaign(
    _campaignId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  releaseMilestone(
    _campaignId: BigNumberish,
    _milestoneIndex: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  requestService(
    campaignId: BigNumberish,
    milestoneIndex: BigNumberish,
    serviceDescription: string,
    serviceProvider: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  serviceProviders(arg0: string, overrides?: CallOverrides): Promise<string>;

  setDAOAddress(
    _daoAddress: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setMilestoneDescription(
    _campaignId: BigNumberish,
    _milestoneIndex: BigNumberish,
    _description: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setMilestoneStatus(
    _campaignId: BigNumberish,
    _milestoneIndex: BigNumberish,
    _status: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  submitBilling(
    campaignId: BigNumberish,
    milestoneIndex: BigNumberish,
    workersCost: BigNumberish,
    materialsCost: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  submitServiceCompletion(
    campaignId: BigNumberish,
    milestoneIndex: BigNumberish,
    serviceProvider: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  viewCampaignDetails(
    _campaignId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber, number, BigNumber] & {
      id: BigNumber;
      beneficiary: string;
      totalAmount: BigNumber;
      status: number;
      milestoneCount: BigNumber;
    }
  >;

  viewMilestoneDetails(
    _campaignId: BigNumberish,
    _milestoneIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, number, BigNumber, BigNumber, BigNumber] & {
      amount: BigNumber;
      status: number;
      workers: BigNumber;
      materialCost: BigNumber;
      daysTaken: BigNumber;
    }
  >;

  callStatic: {
    TotalContributions(
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<Escrow.MilestoneFundingStructOutput[]>;

    VerifyTransaction(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      _workers: BigNumberish,
      _materialCost: BigNumberish,
      _daysTaken: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    approveCampaign(
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    campaignContributions(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    campaigns(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, number, BigNumber, BigNumber] & {
        id: BigNumber;
        beneficiary: string;
        totalAmount: BigNumber;
        status: number;
        currentIndex: BigNumber;
        totalContributions: BigNumber;
      }
    >;

    confirmBilling(
      campaignId: BigNumberish,
      milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    contributeToCampaign(
      _campaignId: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createCampaign(
      _beneficiary: string,
      _totalAmount: BigNumberish,
      _milestoneCount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    daoAddress(overrides?: CallOverrides): Promise<string>;

    donorSpecs(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    escAccount(overrides?: CallOverrides): Promise<string>;

    getCampaignStatus(
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    getDaoAddress(overrides?: CallOverrides): Promise<string>;

    getDetails(
      campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMilestoneCount(
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMilestoneDetails(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, number] & { amount: BigNumber; status: number }>;

    getTransactionHistory(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<Escrow.TransactionHistoryStructOutput>;

    owner(overrides?: CallOverrides): Promise<string>;

    payServiceProvider(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      _serviceProvider: string,
      overrides?: CallOverrides
    ): Promise<void>;

    rejectCampaign(
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    releaseMilestone(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    requestService(
      campaignId: BigNumberish,
      milestoneIndex: BigNumberish,
      serviceDescription: string,
      serviceProvider: string,
      overrides?: CallOverrides
    ): Promise<void>;

    serviceProviders(arg0: string, overrides?: CallOverrides): Promise<string>;

    setDAOAddress(
      _daoAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setMilestoneDescription(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      _description: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setMilestoneStatus(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      _status: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    submitBilling(
      campaignId: BigNumberish,
      milestoneIndex: BigNumberish,
      workersCost: BigNumberish,
      materialsCost: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    submitServiceCompletion(
      campaignId: BigNumberish,
      milestoneIndex: BigNumberish,
      serviceProvider: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    viewCampaignDetails(
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, number, BigNumber] & {
        id: BigNumber;
        beneficiary: string;
        totalAmount: BigNumber;
        status: number;
        milestoneCount: BigNumber;
      }
    >;

    viewMilestoneDetails(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, BigNumber, BigNumber, BigNumber] & {
        amount: BigNumber;
        status: number;
        workers: BigNumber;
        materialCost: BigNumber;
        daysTaken: BigNumber;
      }
    >;
  };

  filters: {
    "AllMilestonesReceived(uint256)"(
      campaignId?: BigNumberish | null
    ): AllMilestonesReceivedEventFilter;
    AllMilestonesReceived(
      campaignId?: BigNumberish | null
    ): AllMilestonesReceivedEventFilter;

    "BillingConfirmed(uint256,uint256)"(
      campaignId?: BigNumberish | null,
      milestoneIndex?: BigNumberish | null
    ): BillingConfirmedEventFilter;
    BillingConfirmed(
      campaignId?: BigNumberish | null,
      milestoneIndex?: BigNumberish | null
    ): BillingConfirmedEventFilter;

    "BillingSubmitted(uint256,uint256,uint256,uint256,uint256)"(
      campaignId?: BigNumberish | null,
      milestoneIndex?: BigNumberish | null,
      workersCost?: null,
      materialsCost?: null,
      totalCost?: null
    ): BillingSubmittedEventFilter;
    BillingSubmitted(
      campaignId?: BigNumberish | null,
      milestoneIndex?: BigNumberish | null,
      workersCost?: null,
      materialsCost?: null,
      totalCost?: null
    ): BillingSubmittedEventFilter;

    "CampaignCompleted(uint256)"(
      campaignId?: BigNumberish | null
    ): CampaignCompletedEventFilter;
    CampaignCompleted(
      campaignId?: BigNumberish | null
    ): CampaignCompletedEventFilter;

    "CampaignCreated(uint256,address,uint256)"(
      campaignId?: BigNumberish | null,
      beneficiary?: string | null,
      totalAmount?: null
    ): CampaignCreatedEventFilter;
    CampaignCreated(
      campaignId?: BigNumberish | null,
      beneficiary?: string | null,
      totalAmount?: null
    ): CampaignCreatedEventFilter;

    "CampaignStatusChanged(uint256,uint8)"(
      campaignId?: BigNumberish | null,
      status?: null
    ): CampaignStatusChangedEventFilter;
    CampaignStatusChanged(
      campaignId?: BigNumberish | null,
      status?: null
    ): CampaignStatusChangedEventFilter;

    "ContributionReceived(address,uint256,uint256)"(
      contributor?: string | null,
      campaignId?: BigNumberish | null,
      targetAmount?: null
    ): ContributionReceivedEventFilter;
    ContributionReceived(
      contributor?: string | null,
      campaignId?: BigNumberish | null,
      targetAmount?: null
    ): ContributionReceivedEventFilter;

    "MilestoneDescriptionUpdated(uint256,uint256,string)"(
      campaignId?: BigNumberish | null,
      milestoneIndex?: BigNumberish | null,
      description?: null
    ): MilestoneDescriptionUpdatedEventFilter;
    MilestoneDescriptionUpdated(
      campaignId?: BigNumberish | null,
      milestoneIndex?: BigNumberish | null,
      description?: null
    ): MilestoneDescriptionUpdatedEventFilter;

    "MilestoneReached(uint256,uint256)"(
      campaignId?: BigNumberish | null,
      milestoneIndex?: null
    ): MilestoneReachedEventFilter;
    MilestoneReached(
      campaignId?: BigNumberish | null,
      milestoneIndex?: null
    ): MilestoneReachedEventFilter;

    "MilestoneUpdated(uint256,uint256,uint8)"(
      campaignId?: BigNumberish | null,
      milestoneIndex?: null,
      status?: null
    ): MilestoneUpdatedEventFilter;
    MilestoneUpdated(
      campaignId?: BigNumberish | null,
      milestoneIndex?: null,
      status?: null
    ): MilestoneUpdatedEventFilter;

    "MilestoneVerified(uint256,uint256)"(
      campaignId?: BigNumberish | null,
      milestoneIndex?: null
    ): MilestoneVerifiedEventFilter;
    MilestoneVerified(
      campaignId?: BigNumberish | null,
      milestoneIndex?: null
    ): MilestoneVerifiedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "RefundIssued(uint256,address,uint256)"(
      id?: null,
      contributor?: null,
      refundAmt?: null
    ): RefundIssuedEventFilter;
    RefundIssued(
      id?: null,
      contributor?: null,
      refundAmt?: null
    ): RefundIssuedEventFilter;

    "ServiceCompletionSubmitted(uint256,uint256,address)"(
      campaignId?: BigNumberish | null,
      milestoneIndex?: BigNumberish | null,
      serviceProvider?: null
    ): ServiceCompletionSubmittedEventFilter;
    ServiceCompletionSubmitted(
      campaignId?: BigNumberish | null,
      milestoneIndex?: BigNumberish | null,
      serviceProvider?: null
    ): ServiceCompletionSubmittedEventFilter;

    "ServiceProviderPaid(uint256,uint256,address,uint256,uint256)"(
      campaignId?: BigNumberish | null,
      milestoneIndex?: BigNumberish | null,
      serviceProvider?: null,
      amount?: null,
      remainingAmount?: null
    ): ServiceProviderPaidEventFilter;
    ServiceProviderPaid(
      campaignId?: BigNumberish | null,
      milestoneIndex?: BigNumberish | null,
      serviceProvider?: null,
      amount?: null,
      remainingAmount?: null
    ): ServiceProviderPaidEventFilter;

    "ServiceRequested(uint256,uint256,string,address)"(
      campaignId?: BigNumberish | null,
      milestoneIndex?: BigNumberish | null,
      serviceDescription?: null,
      serviceProvider?: null
    ): ServiceRequestedEventFilter;
    ServiceRequested(
      campaignId?: BigNumberish | null,
      milestoneIndex?: BigNumberish | null,
      serviceDescription?: null,
      serviceProvider?: null
    ): ServiceRequestedEventFilter;

    "TransactionHistUpdate(uint256,uint256)"(
      campaignId?: BigNumberish | null,
      milestoneIndex?: BigNumberish | null
    ): TransactionHistUpdateEventFilter;
    TransactionHistUpdate(
      campaignId?: BigNumberish | null,
      milestoneIndex?: BigNumberish | null
    ): TransactionHistUpdateEventFilter;
  };

  estimateGas: {
    TotalContributions(
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    VerifyTransaction(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      _workers: BigNumberish,
      _materialCost: BigNumberish,
      _daysTaken: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    approveCampaign(
      _campaignId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    campaignContributions(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    campaigns(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    confirmBilling(
      campaignId: BigNumberish,
      milestoneIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    contributeToCampaign(
      _campaignId: BigNumberish,
      _amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    createCampaign(
      _beneficiary: string,
      _totalAmount: BigNumberish,
      _milestoneCount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    daoAddress(overrides?: CallOverrides): Promise<BigNumber>;

    donorSpecs(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    escAccount(overrides?: CallOverrides): Promise<BigNumber>;

    getCampaignStatus(
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDaoAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getDetails(
      campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMilestoneCount(
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMilestoneDetails(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTransactionHistory(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    payServiceProvider(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      _serviceProvider: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    rejectCampaign(
      _campaignId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    releaseMilestone(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    requestService(
      campaignId: BigNumberish,
      milestoneIndex: BigNumberish,
      serviceDescription: string,
      serviceProvider: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    serviceProviders(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setDAOAddress(
      _daoAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setMilestoneDescription(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      _description: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setMilestoneStatus(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      _status: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    submitBilling(
      campaignId: BigNumberish,
      milestoneIndex: BigNumberish,
      workersCost: BigNumberish,
      materialsCost: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    submitServiceCompletion(
      campaignId: BigNumberish,
      milestoneIndex: BigNumberish,
      serviceProvider: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    viewCampaignDetails(
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    viewMilestoneDetails(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    TotalContributions(
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VerifyTransaction(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      _workers: BigNumberish,
      _materialCost: BigNumberish,
      _daysTaken: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    approveCampaign(
      _campaignId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    campaignContributions(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    campaigns(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    confirmBilling(
      campaignId: BigNumberish,
      milestoneIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    contributeToCampaign(
      _campaignId: BigNumberish,
      _amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    createCampaign(
      _beneficiary: string,
      _totalAmount: BigNumberish,
      _milestoneCount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    daoAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    donorSpecs(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    escAccount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCampaignStatus(
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDaoAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDetails(
      campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMilestoneCount(
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMilestoneDetails(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTransactionHistory(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    payServiceProvider(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      _serviceProvider: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    rejectCampaign(
      _campaignId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    releaseMilestone(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    requestService(
      campaignId: BigNumberish,
      milestoneIndex: BigNumberish,
      serviceDescription: string,
      serviceProvider: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    serviceProviders(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setDAOAddress(
      _daoAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setMilestoneDescription(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      _description: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setMilestoneStatus(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      _status: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    submitBilling(
      campaignId: BigNumberish,
      milestoneIndex: BigNumberish,
      workersCost: BigNumberish,
      materialsCost: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    submitServiceCompletion(
      campaignId: BigNumberish,
      milestoneIndex: BigNumberish,
      serviceProvider: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    viewCampaignDetails(
      _campaignId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    viewMilestoneDetails(
      _campaignId: BigNumberish,
      _milestoneIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
