/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Escrow } from "./Escrow";
export type { GovernorContract } from "./GovernorContract";
export type { IEscrow } from "./IEscrow";
